name: Periodic Health Check

on:
  push:
    branches:
      - master
  schedule:
  - cron: '30 3 * * 0'

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://ronidex.herokuapp.com/health